import type { SkillFastTemplate } from './types';

export const webSkillFastTemplates: SkillFastTemplate[] = [
	{
		id: 'web-design',
		categoryId: 'web',
		title: 'Web Design',
		overview: 'Use this skill for web interface design work where layout, hierarchy, responsive behavior, and visual consistency matter.',
		instructions: [
			'Start by identifying the page or component purpose, the primary user action, and the constraints of the existing UI.',
			'Inspect nearby components, CSS variables, spacing patterns, and interaction states before proposing or editing design details.',
			'Prefer clear hierarchy, responsive constraints, accessible contrast, and restrained visual styling over decorative effects.',
			'When changing code, preserve existing framework and design-system patterns unless the user explicitly asks for a new direction.',
		],
		output: 'Return the concrete UI change or recommendation, including affected files, layout decisions, and any responsive or accessibility caveats.',
		exampleInput: 'Improve the dashboard header and make it fit better on mobile.',
		exampleOutput: 'A focused UI update with responsive spacing, clearer primary action placement, and notes about affected CSS/classes.',
		referenceHints: ['component library docs', 'existing layout files', 'design tokens'],
	},
	{
		id: 'web-styles',
		categoryId: 'web',
		title: 'Web Styles',
		overview: 'Use this skill for CSS, theme, styling, and visual polish tasks in web projects.',
		instructions: [
			'Locate the active styling system first: CSS modules, global CSS, Tailwind, design tokens, or component-scoped styles.',
			'Make style changes with stable selectors and avoid broad overrides that can leak into unrelated screens.',
			'Keep color, spacing, typography, hover, focus, and disabled states consistent with existing tokens and nearby UI.',
			'Verify that text and controls remain readable and do not overlap across narrow and desktop viewports.',
		],
		output: 'Return exact style changes, selectors touched, and any visual states that should be manually checked.',
		exampleInput: 'Make the cards cleaner and less noisy without changing the layout.',
		exampleOutput: 'A restrained style pass that adjusts borders, contrast, spacing, and hover states.',
		referenceHints: ['theme files', 'global CSS', 'component styles'],
	},
	{
		id: 'react-ui',
		categoryId: 'web',
		title: 'React UI',
		overview: 'Use this skill for React UI components, stateful interface behavior, and component composition.',
		instructions: [
			'Inspect component ownership, props, state, and render paths before changing behavior.',
			'Keep state local unless existing patterns require shared state or context.',
			'Preserve accessibility attributes, keyboard paths, and loading/error states when refactoring UI.',
			'Avoid introducing new abstractions unless they remove real duplication or clarify a repeated component contract.',
		],
		output: 'Return component-level changes with props/state reasoning and any manual interaction checks.',
		exampleInput: 'Add a compact edit state to this React card.',
		exampleOutput: 'A component update with scoped state, accessible controls, and preserved surrounding behavior.',
		referenceHints: ['component files', 'hooks', 'tests or stories'],
	},
	{
		id: 'landing-ui',
		categoryId: 'web',
		title: 'Landing UI',
		overview: 'Use this skill for landing pages, marketing sections, hero layouts, and conversion-focused web UI.',
		instructions: [
			'Identify the offer, audience, primary action, and first-viewport constraints before editing content or layout.',
			'Make the product, brand, or object immediately visible and keep the hero focused on the actual offer.',
			'Use real product/context signals where possible instead of generic decorative graphics.',
			'Keep supporting sections scannable, with clear progression from value, proof, details, and action.',
		],
		output: 'Return the page structure or code changes with a short rationale for hierarchy, CTA placement, and responsive behavior.',
		exampleInput: 'Build a landing hero for this developer tool.',
		exampleOutput: 'A first-screen hero and supporting section that reveal the product clearly and keep the CTA visible.',
		referenceHints: ['brand assets', 'product screenshots', 'copy requirements'],
	},
	{
		id: 'accessibility-ui',
		categoryId: 'web',
		title: 'Accessibility UI',
		overview: 'Use this skill for accessibility reviews and fixes in web interfaces.',
		instructions: [
			'Check semantic structure, labels, focus order, keyboard operation, and visible focus before visual-only changes.',
			'Verify contrast, target size, disabled states, and text resizing risks for the affected UI.',
			'Prefer native controls and ARIA only where it clarifies semantics that HTML does not already provide.',
			'When fixing issues, explain the user impact and keep changes narrowly scoped to the failing interaction.',
		],
		output: 'Return issues fixed or found, the affected selectors/components, and any remaining manual checks.',
		exampleInput: 'Review this modal for keyboard and screen reader issues.',
		exampleOutput: 'A focused accessibility pass covering labels, focus trap, escape behavior, and actionable fixes.',
		referenceHints: ['WCAG notes', 'component markup', 'keyboard behavior'],
	},
	{
		id: 'api-client-ui',
		categoryId: 'web',
		title: 'API Client UI',
		overview: 'Use this skill for frontend screens that consume APIs, render server data, or manage client-side request states.',
		instructions: [
			'Identify data sources, request lifecycle, cache strategy, and error/loading states before editing UI.',
			'Keep API concerns separated from presentational components when the codebase already has that pattern.',
			'Render empty, loading, error, partial, and success states deliberately so the UI does not fail silently.',
			'Preserve type safety and avoid assuming response shapes that are not validated or already typed.',
		],
		output: 'Return data-flow changes, affected components, and the states covered by the implementation.',
		exampleInput: 'Add a list that loads project records from this endpoint.',
		exampleOutput: 'A typed API-backed UI with loading, empty, error, and success rendering.',
		referenceHints: ['API client', 'types', 'data fetching hooks'],
	},
];

