import type { SkillFastTemplate } from './types';

export const mobileSkillFastTemplates: SkillFastTemplate[] = [
	{
		id: 'mobile-ui',
		categoryId: 'mobile',
		title: 'Mobile UI',
		overview: 'Use this skill for mobile screens, responsive app layouts, and touch-first UI behavior.',
		instructions: [
			'Identify the target platform, screen density, navigation pattern, and primary touch action before editing UI.',
			'Prioritize readable spacing, stable tap targets, safe-area handling, and predictable scroll behavior.',
			'Respect existing component patterns and avoid desktop-first layout assumptions.',
			'Check loading, empty, error, and offline states when the screen depends on data.',
		],
		output: 'Return mobile-focused UI changes with platform assumptions, affected files, and interaction states.',
		exampleInput: 'Improve this mobile settings screen.',
		exampleOutput: 'A touch-friendly screen update with clearer grouping, safe spacing, and preserved navigation.',
		referenceHints: ['screen components', 'navigation setup', 'platform style guide'],
	},
	{
		id: 'mobile-animation',
		categoryId: 'mobile',
		title: 'Mobile Animation',
		overview: 'Use this skill for mobile motion, transitions, gestures, and animation polish.',
		instructions: [
			'Confirm the animation purpose before adding motion: orientation, feedback, continuity, or delight.',
			'Keep animation durations short, interruptible, and respectful of reduced-motion preferences where available.',
			'Avoid layout shifts and expensive animations that can drop frames on lower-end devices.',
			'Preserve gesture boundaries and conflict rules with scrolling, navigation, and form controls.',
		],
		output: 'Return motion changes with timing, trigger, fallback behavior, and performance notes.',
		exampleInput: 'Add a smooth transition when opening the details panel.',
		exampleOutput: 'A focused transition that supports gesture flow and avoids blocking interaction.',
		referenceHints: ['animation library docs', 'gesture handlers', 'performance notes'],
	},
	{
		id: 'react-native-ui',
		categoryId: 'mobile',
		title: 'React Native UI',
		overview: 'Use this skill for React Native components, screens, styling, and mobile interaction behavior.',
		instructions: [
			'Inspect component structure, navigation route, platform-specific code, and style conventions first.',
			'Use React Native primitives and existing component wrappers consistently.',
			'Account for iOS and Android differences in safe areas, keyboard avoidance, touch feedback, and text rendering.',
			'Keep state changes predictable and avoid unnecessary re-renders in repeated lists or animated areas.',
		],
		output: 'Return React Native changes with platform notes and interaction checks.',
		exampleInput: 'Build a reusable profile row for this React Native app.',
		exampleOutput: 'A typed reusable component with platform-safe spacing and press states.',
		referenceHints: ['navigation files', 'shared components', 'style constants'],
	},
	{
		id: 'flutter-ui',
		categoryId: 'mobile',
		title: 'Flutter UI',
		overview: 'Use this skill for Flutter widgets, app screens, and Dart UI structure.',
		instructions: [
			'Inspect widget hierarchy, state management approach, theme usage, and navigation before changing UI.',
			'Prefer composition with small widgets when it improves readability without fragmenting simple screens.',
			'Use theme values and layout constraints instead of hard-coded visual guesses where possible.',
			'Check adaptive behavior for text scale, small screens, and platform conventions.',
		],
		output: 'Return Flutter widget changes with state, theme, and responsive behavior notes.',
		exampleInput: 'Refactor this Flutter form screen.',
		exampleOutput: 'A clearer widget structure with validation, theme alignment, and stable layout constraints.',
		referenceHints: ['theme files', 'widgets', 'state management'],
	},
	{
		id: 'lynxjs-ui',
		categoryId: 'mobile',
		title: 'LynxJS UI',
		overview: 'Use this skill for LynxJS mobile UI work, cross-platform screens, and frontend patterns around Lynx components.',
		instructions: [
			'Identify the Lynx component structure, styling approach, platform targets, and existing screen patterns first.',
			'Keep UI changes component-scoped and avoid assumptions from browser-only APIs unless the project already uses them safely.',
			'Prioritize touch-friendly layout, predictable sizing, readable text, and platform-aware interaction feedback.',
			'Document any uncertain Lynx runtime constraints instead of silently inventing unsupported behavior.',
		],
		output: 'Return LynxJS-focused UI changes with files touched, runtime assumptions, and manual checks.',
		exampleInput: 'Create a LynxJS card list for mobile results.',
		exampleOutput: 'A component-scoped mobile list with stable spacing, touch states, and clear data assumptions.',
		referenceHints: ['Lynx components', 'runtime docs', 'style files'],
	},
	{
		id: 'mobile-forms',
		categoryId: 'mobile',
		title: 'Mobile Forms',
		overview: 'Use this skill for mobile forms, validation flows, keyboard behavior, and input-heavy screens.',
		instructions: [
			'Inspect validation rules, submit path, keyboard handling, and error display before editing form UI.',
			'Keep labels, hints, errors, and disabled states visible and unambiguous on small screens.',
			'Handle keyboard overlap, input focus, and submit affordances deliberately.',
			'Avoid clearing user input after recoverable validation or network errors.',
		],
		output: 'Return form changes with validation, keyboard, and error-state coverage.',
		exampleInput: 'Improve this mobile signup form.',
		exampleOutput: 'A mobile form with clearer validation, keyboard-safe layout, and resilient submit behavior.',
		referenceHints: ['form schema', 'validation utilities', 'screen layout'],
	},
];

