import type { SkillFastTemplate } from './types';

export const backendSkillFastTemplates: SkillFastTemplate[] = [
	{
		id: 'api-design',
		categoryId: 'backend',
		title: 'API Design',
		overview: 'Use this skill for backend API design, endpoint behavior, contracts, and service boundaries.',
		instructions: [
			'Start by identifying the resource, caller, authorization needs, request shape, and response contract.',
			'Inspect existing routing, validation, error handling, and service patterns before adding endpoints.',
			'Keep API behavior explicit for success, validation failure, auth failure, not found, and server errors.',
			'Prefer typed contracts and small service boundaries over duplicating logic inside route handlers.',
		],
		output: 'Return endpoint changes with request/response shape, validation, and error behavior.',
		exampleInput: 'Add an endpoint for creating projects.',
		exampleOutput: 'A route design with validation, service call, typed response, and failure cases.',
		referenceHints: ['routes', 'schemas', 'service layer'],
	},
	{
		id: 'auth-backend',
		categoryId: 'backend',
		title: 'Auth Backend',
		overview: 'Use this skill for authentication, authorization, sessions, roles, and protected backend flows.',
		instructions: [
			'Identify the auth mechanism, trust boundary, session/token lifecycle, and authorization model first.',
			'Do not weaken existing checks while adding convenience paths or UI-driven assumptions.',
			'Keep authentication separate from authorization and make failure modes explicit.',
			'Check secrets, token storage, redirects, and role checks for the changed flow.',
		],
		output: 'Return auth changes with security assumptions, affected checks, and risk notes.',
		exampleInput: 'Add admin-only access to this route.',
		exampleOutput: 'A protected route update with role validation and clear unauthorized behavior.',
		referenceHints: ['auth middleware', 'session utilities', 'role model'],
	},
	{
		id: 'database-backend',
		categoryId: 'backend',
		title: 'Database Backend',
		overview: 'Use this skill for backend work that reads, writes, validates, or coordinates database data.',
		instructions: [
			'Inspect schema, migrations, query helpers, and transaction boundaries before changing persistence behavior.',
			'Keep data validation and authorization close to the service boundary where existing patterns expect them.',
			'Avoid N+1 queries, unsafe raw SQL, and silent partial writes.',
			'Describe migration or backfill needs when the data model changes.',
		],
		output: 'Return persistence changes with schema/query impact, migration notes, and failure cases.',
		exampleInput: 'Store a project owner and list projects by owner.',
		exampleOutput: 'A backend persistence update with schema impact and typed query behavior.',
		referenceHints: ['schema', 'migrations', 'repositories'],
	},
	{
		id: 'node-backend',
		categoryId: 'backend',
		title: 'Node Backend',
		overview: 'Use this skill for Node.js backend services, middleware, APIs, and runtime behavior.',
		instructions: [
			'Inspect package scripts, runtime version, framework, middleware order, and error handling first.',
			'Use async error handling consistently with the project framework.',
			'Keep environment variables validated and avoid adding hidden runtime requirements.',
			'Prefer small typed modules for business logic instead of large route-level implementations.',
		],
		output: 'Return Node backend changes with runtime assumptions, scripts, and test commands when relevant.',
		exampleInput: 'Add request validation to this Express handler.',
		exampleOutput: 'A Node route update with validation, typed errors, and command notes.',
		referenceHints: ['package.json', 'server entrypoint', 'middleware'],
	},
	{
		id: 'validation-backend',
		categoryId: 'backend',
		title: 'Backend Validation',
		overview: 'Use this skill for backend request validation, schemas, parsing, and error response consistency.',
		instructions: [
			'Find existing schema libraries and validation helpers before adding new validation code.',
			'Validate at the boundary and convert invalid input into clear, stable error responses.',
			'Keep schema names, inferred types, and route contracts synchronized.',
			'Do not trust frontend validation as a substitute for backend validation.',
		],
		output: 'Return schema and handler changes with invalid-input examples and response format.',
		exampleInput: 'Validate this create-user payload.',
		exampleOutput: 'A boundary schema with typed payload and consistent validation errors.',
		referenceHints: ['schema files', 'route handlers', 'error helpers'],
	},
	{
		id: 'observability-backend',
		categoryId: 'backend',
		title: 'Backend Observability',
		overview: 'Use this skill for logs, metrics, traces, diagnostics, and production debugging paths.',
		instructions: [
			'Identify what question the operator needs to answer before adding logs or metrics.',
			'Avoid logging secrets, tokens, PII, or large payloads.',
			'Use existing logger, trace IDs, and metric naming conventions.',
			'Make failures actionable with context, operation name, and safe identifiers.',
		],
		output: 'Return observability changes with event names, fields, and privacy notes.',
		exampleInput: 'Add logging around failed payment sync jobs.',
		exampleOutput: 'Structured logs with safe identifiers, failure reason, and retry context.',
		referenceHints: ['logger setup', 'metrics client', 'job runner'],
	},
];

