import type { SkillFastTemplate } from './types';

export const uiUxSkillFastTemplates: SkillFastTemplate[] = [
	{
		id: 'design-system',
		categoryId: 'ui-ux',
		title: 'Design System',
		overview: 'Use this skill for design-system rules, reusable UI patterns, tokens, and component consistency.',
		instructions: [
			'Inventory existing tokens, components, variants, and naming conventions before creating new primitives.',
			'Prefer extending established patterns over adding one-off component styles.',
			'Define states, sizes, accessibility behavior, and usage constraints for reusable pieces.',
			'Keep examples realistic and tied to actual product surfaces.',
		],
		output: 'Return design-system decisions with component/token impact and usage guidance.',
		exampleInput: 'Create rules for buttons and cards.',
		exampleOutput: 'A component rule set covering variants, states, tokens, and usage constraints.',
		referenceHints: ['tokens', 'component library', 'style guide'],
	},
	{
		id: 'visual-polish',
		categoryId: 'ui-ux',
		title: 'Visual Polish',
		overview: 'Use this skill for subtle UI refinement, readability, spacing, and visual balance.',
		instructions: [
			'Identify what feels off: hierarchy, spacing, contrast, density, alignment, or interaction feedback.',
			'Make restrained changes that preserve the product character and existing theme.',
			'Check hover, focus, selected, disabled, loading, and empty states.',
			'Keep visual changes connected to usability, not decoration alone.',
		],
		output: 'Return polish changes with the visual problem solved and states checked.',
		exampleInput: 'Make this sidebar feel cleaner and less cramped.',
		exampleOutput: 'A focused spacing and contrast pass with preserved density.',
		referenceHints: ['screenshots', 'CSS', 'theme variables'],
	},
	{
		id: 'accessibility-review',
		categoryId: 'ui-ux',
		title: 'Accessibility Review',
		overview: 'Use this skill for UI accessibility audits, remediation, and interaction clarity.',
		instructions: [
			'Review semantic structure, labels, keyboard operation, focus visibility, and contrast before visual changes.',
			'Prioritize blockers that prevent task completion over cosmetic issues.',
			'Use native elements when possible and keep ARIA minimal and accurate.',
			'Document remaining manual checks when automated proof is not available.',
		],
		output: 'Return accessibility findings or fixes ordered by user impact.',
		exampleInput: 'Audit this settings panel for accessibility.',
		exampleOutput: 'A prioritized list of accessibility fixes with exact affected controls.',
		referenceHints: ['markup', 'keyboard flow', 'WCAG checklist'],
	},
	{
		id: 'layout-system',
		categoryId: 'ui-ux',
		title: 'Layout System',
		overview: 'Use this skill for responsive layout rules, grids, spacing systems, and screen structure.',
		instructions: [
			'Identify content hierarchy, viewport constraints, and repeated layout patterns first.',
			'Use stable constraints such as grid tracks, min/max sizes, and aspect ratios to prevent layout shift.',
			'Keep typography scale appropriate to the surface density.',
			'Verify narrow, normal, and wide viewport behavior for affected layouts.',
		],
		output: 'Return layout changes with responsive rules and any known breakpoint behavior.',
		exampleInput: 'Create a layout system for a compact tool panel.',
		exampleOutput: 'A constrained layout with stable rows, predictable overflow, and responsive behavior.',
		referenceHints: ['layout CSS', 'component structure', 'screenshots'],
	},
	{
		id: 'motion-design',
		categoryId: 'ui-ux',
		title: 'Motion Design',
		overview: 'Use this skill for interface motion, transitions, and animation systems.',
		instructions: [
			'Start from the purpose of motion: state change, continuity, feedback, or spatial orientation.',
			'Use restrained timing, easing, and distance that fit the product density.',
			'Respect reduced-motion preferences and avoid motion that blocks task completion.',
			'Prefer animating transform and opacity when possible.',
		],
		output: 'Return motion decisions with triggers, timing, fallback, and reduced-motion behavior.',
		exampleInput: 'Add a transition between create steps.',
		exampleOutput: 'A transition pattern that clarifies progression and preserves responsiveness.',
		referenceHints: ['transition CSS', 'state changes', 'motion tokens'],
	},
	{
		id: 'figma-handoff',
		categoryId: 'ui-ux',
		title: 'Figma Handoff',
		overview: 'Use this skill for translating Figma or design specs into implementation-ready UI guidance.',
		instructions: [
			'Extract layout, spacing, typography, color, component states, and responsive intent from the design source.',
			'Map design tokens to existing code tokens before inventing new values.',
			'Call out ambiguities and implementation constraints that need product or design confirmation.',
			'Produce code-oriented guidance with exact components, files, or CSS concepts where possible.',
		],
		output: 'Return implementation guidance or changes tied to the design spec and existing code system.',
		exampleInput: 'Implement this Figma card in our app.',
		exampleOutput: 'A token-aware implementation plan with component mapping and unresolved design questions.',
		referenceHints: ['Figma notes', 'tokens', 'component library'],
	},
];

