import type { SkillFastTemplate } from './types';

export const aiSkillFastTemplates: SkillFastTemplate[] = [
	{
		id: 'rag-workflow',
		categoryId: 'ai',
		title: 'RAG Workflow',
		overview: 'Use this skill for retrieval-augmented generation, knowledge grounding, embeddings, and context assembly.',
		instructions: [
			'Identify source documents, freshness needs, chunking strategy, retrieval query, and answer constraints.',
			'Separate ingestion, indexing, retrieval, reranking, prompt assembly, and answer validation concerns.',
			'Preserve citations or source references when the product requires traceability.',
			'Test with realistic queries that include missing, ambiguous, and conflicting information.',
		],
		output: 'Return a RAG plan or implementation with data flow, retrieval choices, and evaluation checks.',
		exampleInput: 'Design RAG for internal docs search.',
		exampleOutput: 'A staged RAG pipeline with indexing, retrieval, prompt assembly, and eval cases.',
		referenceHints: ['document sources', 'embedding provider', 'vector store'],
	},
	{
		id: 'agent-workflow',
		categoryId: 'ai',
		title: 'Agent Workflow',
		overview: 'Use this skill for agentic workflows, tool use, planning loops, and multi-step automation.',
		instructions: [
			'Define the agent goal, allowed tools, stop conditions, and human approval boundaries first.',
			'Keep tool schemas narrow, observable, and resilient to partial failure.',
			'Separate planning, tool execution, result validation, and final response.',
			'Add safeguards for destructive actions, external calls, and high-cost loops.',
		],
		output: 'Return an agent workflow with tools, control flow, safety boundaries, and test scenarios.',
		exampleInput: 'Create an agent that triages support tickets.',
		exampleOutput: 'A tool-driven workflow with classification, routing, confidence checks, and escalation.',
		referenceHints: ['tool schemas', 'agent runtime', 'approval rules'],
	},
	{
		id: 'openai-integration',
		categoryId: 'ai',
		title: 'OpenAI Integration',
		overview: 'Use this skill for OpenAI API integrations, model calls, structured outputs, and product workflows.',
		instructions: [
			'Identify the user task, latency/cost constraints, output shape, and failure handling before adding model calls.',
			'Use structured outputs or schemas where downstream code depends on exact fields.',
			'Keep prompts explicit about context, constraints, and refusal/fallback behavior.',
			'Avoid logging sensitive prompts or model outputs unless the project already has safe telemetry rules.',
		],
		output: 'Return integration changes with model call shape, schema, retries, and error behavior.',
		exampleInput: 'Add AI-generated summaries for project notes.',
		exampleOutput: 'A schema-backed model call with prompt inputs, validation, and fallback handling.',
		referenceHints: ['API client', 'schema types', 'prompt files'],
	},
	{
		id: 'prompt-engineering',
		categoryId: 'ai',
		title: 'Prompt Engineering',
		overview: 'Use this skill for prompts, system instructions, task framing, and output control.',
		instructions: [
			'Start by defining the desired behavior, bad outputs to avoid, and evaluation examples.',
			'Make instructions concrete, scoped, and testable instead of relying on vague style requests.',
			'Include examples only when they reduce ambiguity or enforce a format.',
			'Keep prompts maintainable by separating reusable policy, task context, and user input.',
		],
		output: 'Return prompt changes with rationale and example inputs that should pass.',
		exampleInput: 'Improve this prompt so summaries are shorter and structured.',
		exampleOutput: 'A tighter prompt with schema expectations and regression examples.',
		referenceHints: ['prompt files', 'eval examples', 'output schema'],
	},
	{
		id: 'vector-search',
		categoryId: 'ai',
		title: 'Vector Search',
		overview: 'Use this skill for embeddings, vector databases, semantic search, and retrieval ranking.',
		instructions: [
			'Identify corpus size, update frequency, metadata filters, and retrieval quality expectations.',
			'Choose chunking and embedding strategy based on content shape, not defaults alone.',
			'Use metadata filters and reranking when plain similarity is likely to return noisy results.',
			'Measure retrieval with representative queries and expected source documents.',
		],
		output: 'Return vector search design or changes with indexing, query, filters, and evaluation notes.',
		exampleInput: 'Add semantic search for help articles.',
		exampleOutput: 'An embedding and retrieval plan with chunking, metadata filters, and eval queries.',
		referenceHints: ['vector DB', 'embedding model', 'source corpus'],
	},
	{
		id: 'ai-evals',
		categoryId: 'ai',
		title: 'AI Evals',
		overview: 'Use this skill for AI evaluation sets, regression checks, quality rubrics, and model behavior tests.',
		instructions: [
			'Define the behavior to protect and collect realistic passing and failing examples.',
			'Use deterministic checks for format and rubric-based checks for subjective quality.',
			'Track regressions by scenario instead of relying on a single aggregate score.',
			'Include edge cases for missing context, ambiguity, unsafe requests, and malformed outputs.',
		],
		output: 'Return eval cases, rubric, runner notes, and how failures should be interpreted.',
		exampleInput: 'Create evals for the support-ticket classifier.',
		exampleOutput: 'A scenario-based eval set with expected labels, edge cases, and scoring rules.',
		referenceHints: ['eval runner', 'sample data', 'quality rubric'],
	},
];

