import type { SkillFastTemplate } from './types';

export const testingSkillFastTemplates: SkillFastTemplate[] = [
	{
		id: 'e2e-testing',
		categoryId: 'testing',
		title: 'E2E Testing',
		overview: 'Use this skill for end-to-end tests, browser workflows, and user-path verification.',
		instructions: [
			'Identify the critical user path, setup data, stable selectors, and expected final state before writing tests.',
			'Prefer user-visible interactions and assertions over implementation details.',
			'Make tests resilient to timing by waiting on meaningful UI or network state.',
			'Keep test data isolated and clean up when the project pattern requires it.',
		],
		output: 'Return E2E test changes with covered path, selectors, setup, and command to run.',
		exampleInput: 'Add an E2E test for creating a project.',
		exampleOutput: 'A stable test that covers login/setup, create flow, and final assertion.',
		referenceHints: ['test config', 'fixtures', 'page objects'],
	},
	{
		id: 'unit-testing',
		categoryId: 'testing',
		title: 'Unit Testing',
		overview: 'Use this skill for focused unit tests around functions, classes, and small components.',
		instructions: [
			'Identify the behavior contract and edge cases before writing assertions.',
			'Keep mocks minimal and avoid testing private implementation details.',
			'Cover success, failure, boundary, and invalid input paths where they matter.',
			'Use existing test utilities, naming, and runner conventions.',
		],
		output: 'Return unit tests with behavior covered and command to run.',
		exampleInput: 'Add tests for this parser.',
		exampleOutput: 'A focused test suite covering valid input, invalid input, and edge cases.',
		referenceHints: ['test utilities', 'fixtures', 'runner config'],
	},
	{
		id: 'component-testing',
		categoryId: 'testing',
		title: 'Component Testing',
		overview: 'Use this skill for component-level UI tests, interaction states, and render behavior.',
		instructions: [
			'Identify component inputs, user interactions, accessible labels, and visible output first.',
			'Test behavior through user-facing queries instead of internal class names when possible.',
			'Cover loading, empty, error, disabled, and selected states when the component supports them.',
			'Keep tests scoped so failures point to a clear UI contract.',
		],
		output: 'Return component tests with interactions, assertions, and state coverage.',
		exampleInput: 'Test this dropdown component.',
		exampleOutput: 'A component test covering open, select, keyboard, disabled, and empty states.',
		referenceHints: ['testing library setup', 'component props', 'fixtures'],
	},
	{
		id: 'api-testing',
		categoryId: 'testing',
		title: 'API Testing',
		overview: 'Use this skill for API route tests, integration checks, and contract verification.',
		instructions: [
			'Identify request shape, auth setup, data setup, response contract, and error cases.',
			'Use isolated test data and avoid depending on shared mutable state.',
			'Assert status codes, response body, side effects, and authorization behavior.',
			'Keep tests aligned with existing integration-test helpers and database lifecycle.',
		],
		output: 'Return API tests with setup, requests, assertions, and run command.',
		exampleInput: 'Test the create-user API route.',
		exampleOutput: 'Integration tests for success, validation failure, duplicate user, and unauthorized access.',
		referenceHints: ['API test helpers', 'database fixtures', 'auth utilities'],
	},
	{
		id: 'accessibility-testing',
		categoryId: 'testing',
		title: 'Accessibility Testing',
		overview: 'Use this skill for accessibility-focused test coverage and manual verification plans.',
		instructions: [
			'Identify the accessibility contract: names, roles, focus movement, keyboard operation, and contrast risks.',
			'Automate what can be reliably asserted and document manual checks for visual or assistive-tech behavior.',
			'Use role and label queries to keep tests close to user experience.',
			'Include regression cases for previously broken keyboard or focus paths.',
		],
		output: 'Return accessibility tests or checklist with exact user impact and coverage limits.',
		exampleInput: 'Add accessibility tests for the modal.',
		exampleOutput: 'Tests for role/name, focus behavior, escape close, and labelled controls.',
		referenceHints: ['accessibility utilities', 'component markup', 'keyboard flow'],
	},
	{
		id: 'visual-regression',
		categoryId: 'testing',
		title: 'Visual Regression',
		overview: 'Use this skill for screenshot tests, visual diff checks, and UI regression workflows.',
		instructions: [
			'Identify stable viewport sizes, deterministic data, fonts, animations, and theme modes before screenshots.',
			'Disable or wait for animation and network noise that can create flaky diffs.',
			'Capture states that matter: default, hover/focus where supported, empty, error, and responsive variants.',
			'Keep snapshot names and update rules clear so diffs are reviewable.',
		],
		output: 'Return visual test setup with viewports, states, and flake controls.',
		exampleInput: 'Add screenshot coverage for the settings page.',
		exampleOutput: 'A visual test suite with stable data, desktop/mobile screenshots, and diff guidance.',
		referenceHints: ['screenshot runner', 'fixture data', 'theme setup'],
	},
];

