import type { SkillFastTemplate } from './types';

export const securitySkillFastTemplates: SkillFastTemplate[] = [
	{
		id: 'auth-security',
		categoryId: 'security',
		title: 'Auth Security',
		overview: 'Use this skill for authentication and authorization security reviews or implementations.',
		instructions: [
			'Identify identity source, session/token storage, authorization model, and trust boundaries.',
			'Check bypass paths, confused-deputy risks, insecure redirects, and missing server-side authorization.',
			'Keep secrets and tokens out of logs, URLs, and client-visible state unless explicitly safe.',
			'Preserve existing security posture while improving usability or developer ergonomics.',
		],
		output: 'Return security changes or findings with risk, impact, and verification steps.',
		exampleInput: 'Review this login flow for security issues.',
		exampleOutput: 'A prioritized auth review with concrete fixes and residual risks.',
		referenceHints: ['auth middleware', 'session config', 'route guards'],
	},
	{
		id: 'oauth-security',
		categoryId: 'security',
		title: 'OAuth Security',
		overview: 'Use this skill for OAuth, OIDC, redirects, scopes, and provider integration security.',
		instructions: [
			'Identify provider, flow type, redirect URIs, scopes, state/nonce handling, and token storage.',
			'Validate redirect handling and do not trust user-controlled callback targets.',
			'Use least-privilege scopes and document why each scope is needed.',
			'Handle token refresh, revocation, and error callbacks deliberately.',
		],
		output: 'Return OAuth changes with flow assumptions, security checks, and provider-specific caveats.',
		exampleInput: 'Add OAuth login with GitHub.',
		exampleOutput: 'A provider integration with state validation, callback handling, and scope notes.',
		referenceHints: ['provider docs', 'auth config', 'callback route'],
	},
	{
		id: 'secrets-security',
		categoryId: 'security',
		title: 'Secrets Security',
		overview: 'Use this skill for environment variables, credentials, secret scanning, and safe configuration.',
		instructions: [
			'Inventory where secrets are read, stored, logged, and passed to external services.',
			'Validate required environment variables at startup or command boundary.',
			'Never add real secrets to examples, tests, docs, or committed config.',
			'Prefer centralized config helpers over scattered process environment reads.',
		],
		output: 'Return secret-handling changes with validation, redaction, and setup notes.',
		exampleInput: 'Clean up API key handling in this service.',
		exampleOutput: 'A safer config path with validation and no secret leakage in logs.',
		referenceHints: ['env schema', 'config helpers', 'deployment docs'],
	},
	{
		id: 'owasp-review',
		categoryId: 'security',
		title: 'OWASP Review',
		overview: 'Use this skill for practical OWASP-style reviews of web and backend code.',
		instructions: [
			'Scope the review to the changed surface and identify relevant OWASP categories.',
			'Prioritize exploitable issues over theoretical concerns.',
			'Check input validation, access control, injection risks, sensitive data exposure, and dependency/config risks.',
			'Provide fixes that fit the codebase instead of generic security advice.',
		],
		output: 'Return findings ordered by severity with evidence, exploit path, and concrete remediation.',
		exampleInput: 'Review this API route for OWASP risks.',
		exampleOutput: 'A severity-ordered review with exact code references and fixes.',
		referenceHints: ['route code', 'validation schemas', 'auth rules'],
	},
	{
		id: 'api-security',
		categoryId: 'security',
		title: 'API Security',
		overview: 'Use this skill for securing API endpoints, request validation, authorization, and abuse controls.',
		instructions: [
			'Identify caller identity, authorization requirements, input trust level, rate limits, and data exposure.',
			'Validate input server-side and avoid leaking sensitive details in error responses.',
			'Check object-level authorization for every resource read or write.',
			'Consider idempotency, replay, rate limiting, and audit logging for sensitive operations.',
		],
		output: 'Return API security changes with checks, failure modes, and residual risks.',
		exampleInput: 'Secure the project delete endpoint.',
		exampleOutput: 'An endpoint update with ownership checks, validation, audit log, and safe errors.',
		referenceHints: ['routes', 'auth context', 'rate limiter'],
	},
	{
		id: 'encryption-security',
		categoryId: 'security',
		title: 'Encryption Security',
		overview: 'Use this skill for encryption, hashing, signing, key handling, and crypto-related decisions.',
		instructions: [
			'Identify whether the need is encryption, hashing, signing, or transport security before choosing tools.',
			'Use established libraries and project-approved primitives instead of custom crypto.',
			'Keep key management, rotation, storage, and error handling explicit.',
			'Document compatibility and migration risks when changing existing encrypted data.',
		],
		output: 'Return crypto-related guidance or changes with primitive choice, key handling, and migration notes.',
		exampleInput: 'Store these tokens securely.',
		exampleOutput: 'A token storage design with encryption boundary, key source, and rotation caveats.',
		referenceHints: ['crypto utilities', 'key management', 'data model'],
	},
];

