import type { SkillFastTemplate } from './types';

export const databaseSkillFastTemplates: SkillFastTemplate[] = [
	{
		id: 'database-schema',
		categoryId: 'database',
		title: 'Database Schema',
		overview: 'Use this skill for database schema design, data modeling, constraints, and relationships.',
		instructions: [
			'Identify entities, relationships, cardinality, lifecycle, and query patterns before changing schema.',
			'Use constraints, indexes, and defaults to protect data integrity where the database should enforce rules.',
			'Consider migration, backfill, rollback, and compatibility with existing data.',
			'Keep naming consistent with current tables, models, and repository conventions.',
		],
		output: 'Return schema guidance or changes with migration impact, indexes, and data-integrity notes.',
		exampleInput: 'Design tables for projects and members.',
		exampleOutput: 'A relational model with constraints, indexes, and migration considerations.',
		referenceHints: ['schema files', 'migrations', 'query patterns'],
	},
	{
		id: 'prisma-database',
		categoryId: 'database',
		title: 'Prisma Database',
		overview: 'Use this skill for Prisma schema, migrations, Prisma Client usage, and database workflows.',
		instructions: [
			'Inspect schema.prisma, migrations, generated client usage, and existing model naming first.',
			'Keep Prisma schema changes aligned with migration and deployment workflow.',
			'Use typed Prisma Client calls and avoid duplicating data access patterns.',
			'Call out when data migration or backfill is required beyond schema migration.',
		],
		output: 'Return Prisma schema/client changes with migration and query notes.',
		exampleInput: 'Add project memberships to Prisma.',
		exampleOutput: 'A Prisma model update with relations, migration notes, and typed query examples.',
		referenceHints: ['schema.prisma', 'migrations', 'Prisma Client usage'],
	},
	{
		id: 'supabase-database',
		categoryId: 'database',
		title: 'Supabase Database',
		overview: 'Use this skill for Supabase Postgres, RLS, client queries, and data access patterns.',
		instructions: [
			'Identify tables, policies, auth context, client/server boundary, and data exposure risks first.',
			'Use Row Level Security deliberately and test policies for allowed and denied users.',
			'Keep SQL migrations, generated types, and client queries synchronized.',
			'Avoid exposing service-role behavior to client code.',
		],
		output: 'Return Supabase changes with RLS policy, migration, and client/server usage notes.',
		exampleInput: 'Add private notes in Supabase.',
		exampleOutput: 'A table and RLS plan with typed client access and denied-access checks.',
		referenceHints: ['SQL migrations', 'RLS policies', 'Supabase client'],
	},
	{
		id: 'postgres-database',
		categoryId: 'database',
		title: 'Postgres Database',
		overview: 'Use this skill for Postgres schema, SQL queries, indexes, migrations, and performance.',
		instructions: [
			'Inspect table shape, query patterns, indexes, constraints, and transaction boundaries before changing SQL.',
			'Use indexes based on actual filters, joins, ordering, and uniqueness needs.',
			'Prefer explicit transactions for multi-step writes that must remain consistent.',
			'Consider migration locks, backfills, and rollback strategy for production data.',
		],
		output: 'Return SQL/schema changes with query impact, indexes, migration notes, and transaction behavior.',
		exampleInput: 'Optimize project search in Postgres.',
		exampleOutput: 'A query and index plan with expected access pattern and migration caveats.',
		referenceHints: ['SQL migrations', 'queries', 'database explain output'],
	},
	{
		id: 'mongodb-database',
		categoryId: 'database',
		title: 'MongoDB Database',
		overview: 'Use this skill for MongoDB document models, indexes, aggregation, and NoSQL data access.',
		instructions: [
			'Identify document shape, access patterns, update frequency, and consistency needs before modeling data.',
			'Design indexes around concrete query filters and sort patterns.',
			'Avoid unbounded document growth and ambiguous partial update behavior.',
			'Keep validation and serialization aligned with application types.',
		],
		output: 'Return MongoDB changes with document shape, indexes, queries, and consistency notes.',
		exampleInput: 'Model user notifications in MongoDB.',
		exampleOutput: 'A document model with indexes, query examples, and growth considerations.',
		referenceHints: ['collections', 'indexes', 'query code'],
	},
	{
		id: 'database-migrations',
		categoryId: 'database',
		title: 'Database Migrations',
		overview: 'Use this skill for migration planning, schema rollout, backfills, and rollback-safe data changes.',
		instructions: [
			'Identify whether the change is additive, destructive, data-moving, or compatibility-sensitive.',
			'Plan deploy order so old and new application versions can tolerate transitional schema where needed.',
			'Separate schema migration, data backfill, validation, and cleanup when risk is non-trivial.',
			'Document rollback limits honestly, especially after destructive or large data changes.',
		],
		output: 'Return migration steps with deploy order, backfill plan, validation, and rollback notes.',
		exampleInput: 'Rename a column without downtime.',
		exampleOutput: 'A staged migration plan with dual-write/read compatibility and cleanup phase.',
		referenceHints: ['migration tool', 'deployment process', 'data volume'],
	},
];

