/**
 * Graph builder — orchestrates graphify to generate project dependency graph.
 * Produces graph.json and enriches project-map.md with relationship data.
 */

import * as childProcess from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

type GraphBuildResult = {
	success: boolean;
	graphJsonPath?: string;
	graphData?: Record<string, any>;
	durationMs?: number;
	error?: string;
};

const spawnAsync = (
	command: string,
	args: string[],
	cwd: string
): Promise<{ code: number; stdout: string; stderr: string }> => {
	return new Promise((resolve) => {
		const startTime = Date.now();
		const proc = childProcess.spawn(command, args, {
			cwd,
			timeout: 120000,
			stdio: ['ignore', 'pipe', 'pipe']
		});

		let stdout = '';
		let stderr = '';

		if (proc.stdout) {proc.stdout.on('data', (data) => (stdout += data.toString()));}
		if (proc.stderr) {proc.stderr.on('data', (data) => (stderr += data.toString()));}

		proc.on('close', (code) => {
			const durationMs = Date.now() - startTime;
			resolve({ code: code ?? 1, stdout, stderr });
		});

		proc.on('error', () => {
			const durationMs = Date.now() - startTime;
			resolve({ code: 1, stdout, stderr });
		});
	});
};

export class GraphBuilder {
	async buildGraph(pythonPath: string, projectRoot: string): Promise<GraphBuildResult> {
		try {
			const startTime = Date.now();
			const graphDir = path.join(projectRoot, '.f1');

			if (!fs.existsSync(graphDir)) {
				fs.mkdirSync(graphDir, { recursive: true });
			}

			const result = await spawnAsync(pythonPath, [
				'-m',
				'graphify',
				'--output',
				path.join(graphDir, 'graph.json'),
				'--format',
				'json',
				projectRoot
			], projectRoot);

			const durationMs = Date.now() - startTime;

			if (result.code === 0) {
				const graphJsonPath = path.join(graphDir, 'graph.json');

				let graphData;
				try {
					const content = fs.readFileSync(graphJsonPath, 'utf8');
					graphData = JSON.parse(content);
				} catch {
					graphData = undefined;
				}

				return {
					success: true,
					graphJsonPath,
					graphData,
					durationMs
				};
			}

			return {
				success: false,
				durationMs,
				error: result.stderr || 'Graphify build failed'
			};
		} catch (error) {
			return {
				success: false,
				error: error instanceof Error ? error.message : String(error)
			};
		}
	}

	enrichProjectMap(projectRoot: string, graphData?: Record<string, any>): string {
		try {
			const mapPath = path.join(projectRoot, '.f1', 'project-map.md');
			let content = '';

			if (fs.existsSync(mapPath)) {
				content = fs.readFileSync(mapPath, 'utf8');
			}

			if (!content) {
				content = this.generateBaseProjectMap(projectRoot);
			}

			if (graphData && graphData.nodes && Array.isArray(graphData.nodes)) {
				const entry = graphData.nodes.find((n: any) => n.type === 'entry' || n.name === 'index');
				const modules = graphData.nodes.filter((n: any) => n.type === 'module').length;
				const dependencies = graphData.nodes.filter((n: any) => n.type === 'dependency').length;

				const section = `\n## Graph Analysis\n\n- **Entry points:** ${entry ? 1 : 0}\n- **Modules:** ${modules}\n- **Dependencies:** ${dependencies}\n\n`;

				if (!content.includes('## Graph Analysis')) {
					content += section;
				}
			}

			fs.writeFileSync(mapPath, content, 'utf8');
			return mapPath;
		} catch (error) {
			console.error('[graph-builder] enrichProjectMap failed:', error);
			return path.join(projectRoot, '.f1', 'project-map.md');
		}
	}

	private generateBaseProjectMap(projectRoot: string): string {
		const lines = [
			'# Project Map',
			'',
			'> Auto-generated by F1 "My Memory" — a structural summary for AI context.',
			'> Edit and commit this file to share project understanding with your team.',
			''
		];

		const pkgPath = path.join(projectRoot, 'package.json');
		try {
			const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
			lines.push('## Package');
			if (pkg.name) {lines.push(`- **Name:** ${pkg.name}${pkg.version ? ` (v${pkg.version})` : ''}`);}
			if (pkg.description) {lines.push(`- **Description:** ${pkg.description}`);}
			const entry = pkg.main || pkg.module;
			if (entry) {lines.push(`- **Entry point:** \`${entry}\``);}
			lines.push('');
		} catch {
			/* ignore */
		}

		const dirs = this.listTopLevelDirs(projectRoot);
		if (dirs.length) {
			lines.push('## Folders');
			for (const dir of dirs) {
				lines.push(`- \`${dir}/\``);
			}
		}

		return lines.join('\n');
	}

	private listTopLevelDirs(root: string): string[] {
		const ignored = new Set(['node_modules', 'dist', 'out', 'build', '.next', '.git', '.f1']);
		try {
			return fs
				.readdirSync(root, { withFileTypes: true })
				.filter((e) => e.isDirectory() && !e.name.startsWith('.') && !ignored.has(e.name))
				.map((e) => e.name)
				.sort();
		} catch {
			return [];
		}
	}
}
