/**
 * Renders a ProjectScan into the Markdown `project-map.md` that CLIs read.
 * Pure string building + a single fs write — no Python, no AI tokens.
 *
 * After a graphify build the map points the reader at the richer graph files
 * (`graph.json` + `GRAPH_REPORT.md`) that sit next to it in `.f1/`.
 */

import * as fs from 'fs';
import * as path from 'path';
import { MEMORY_DIR, MEMORY_MAP_FILE } from '../core/memory-paths';
import type { ProjectScan } from './scan-project';

const MAX_DEPS = 20;

export type RenderOptions = { hasGraph?: boolean };

/** Build the Markdown body (kept separate so it's easy to test/preview). */
export const renderProjectMap = (scan: ProjectScan, options: RenderOptions = {}): string => {
	const lines: string[] = [
		'# Project map',
		'',
		'> Generated by F1 "My Memory" — a structural summary so an AI can grasp this',
		'> project without scanning every file. Safe to edit and commit.',
		''
	];

	const hasPackage = scan.name || scan.description || scan.entryPoint || scan.scripts.length || scan.dependencies.length;
	if (hasPackage) {
		lines.push('## Package');
		if (scan.name) {
			lines.push(`- **Name:** ${scan.name}${scan.version ? ` (v${scan.version})` : ''}`);
		}
		if (scan.description) {
			lines.push(`- **Description:** ${scan.description}`);
		}
		if (scan.entryPoint) {
			lines.push(`- **Entry point:** \`${scan.entryPoint}\``);
		}
		if (scan.scripts.length) {
			lines.push(`- **Scripts:** ${scan.scripts.map((s) => `\`${s}\``).join(', ')}`);
		}
		if (scan.dependencies.length) {
			const shown = scan.dependencies.slice(0, MAX_DEPS).join(', ');
			const more = scan.dependencies.length > MAX_DEPS ? ', …' : '';
			lines.push(`- **Dependencies:** ${shown}${more}`);
		}
		lines.push('');
	}

	if (scan.topLevelFolders.length) {
		lines.push('## Top-level folders');
		for (const folder of scan.topLevelFolders) {
			lines.push(`- \`${folder}/\``);
		}
		lines.push('');
	}

	lines.push('---');
	lines.push('');
	if (options.hasGraph) {
		lines.push('## Dependency graph');
		lines.push('');
		lines.push('A full code graph for this project is available next to this file:');
		lines.push('- `./GRAPH_REPORT.md` — human-readable highlights of the graph.');
		lines.push('- `./graph.json` — the full import/call graph (built locally by graphify).');
		lines.push('');
	} else {
		lines.push('_Starter map. Build the graph (brain button) to enrich this with import/call relationships._');
		lines.push('');
	}
	return lines.join('\n');
};

/** Write `.f1/project-map.md`, overwriting any existing map. */
export const writeProjectMap = (root: string, scan: ProjectScan, options: RenderOptions = {}): string => {
	const mapPath = path.join(root, MEMORY_DIR, MEMORY_MAP_FILE);
	fs.mkdirSync(path.dirname(mapPath), { recursive: true });
	fs.writeFileSync(mapPath, renderProjectMap(scan, options), 'utf8');
	return mapPath;
};
