/**
 * Renders a ProjectScan into the Markdown `project-map.md` that CLIs read.
 * Pure string building + a single fs write — no Python, no AI tokens.
 */

import * as fs from 'fs';
import * as path from 'path';
import { MEMORY_DIR, MEMORY_MAP_FILE } from '../core/memory-paths';
import type { ProjectScan } from './scan-project';

const MAX_DEPS = 20;

/** Build the Markdown body (kept separate so it's easy to test/preview). */
export const renderProjectMap = (scan: ProjectScan): string => {
	const lines: string[] = [
		'# Project map',
		'',
		'> Generated by F1 "My Memory" — a lightweight structural summary so an AI',
		'> can grasp this project without scanning every file. Safe to edit and commit.',
		''
	];

	const hasPackage = scan.name || scan.description || scan.entryPoint || scan.scripts.length || scan.dependencies.length;
	if (hasPackage) {
		lines.push('## Package');
		if (scan.name) {
			lines.push(`- **Name:** ${scan.name}${scan.version ? ` (v${scan.version})` : ''}`);
		}
		if (scan.description) {
			lines.push(`- **Description:** ${scan.description}`);
		}
		if (scan.entryPoint) {
			lines.push(`- **Entry point:** \`${scan.entryPoint}\``);
		}
		if (scan.scripts.length) {
			lines.push(`- **Scripts:** ${scan.scripts.map((s) => `\`${s}\``).join(', ')}`);
		}
		if (scan.dependencies.length) {
			const shown = scan.dependencies.slice(0, MAX_DEPS).join(', ');
			const more = scan.dependencies.length > MAX_DEPS ? ', …' : '';
			lines.push(`- **Dependencies:** ${shown}${more}`);
		}
		lines.push('');
	}

	if (scan.topLevelFolders.length) {
		lines.push('## Top-level folders');
		for (const folder of scan.topLevelFolders) {
			lines.push(`- \`${folder}/\``);
		}
		lines.push('');
	}

	lines.push('---');
	lines.push('');
	lines.push('_Starter map. A full graph build can later enrich this with import/call relationships._');
	lines.push('');
	return lines.join('\n');
};

/** Write `.f1/project-map.md`, overwriting any existing map. */
export const writeProjectMap = (root: string, scan: ProjectScan): string => {
	const mapPath = path.join(root, MEMORY_DIR, MEMORY_MAP_FILE);
	fs.mkdirSync(path.dirname(mapPath), { recursive: true });
	fs.writeFileSync(mapPath, renderProjectMap(scan), 'utf8');
	return mapPath;
};
