import type { TechnologyRule } from '../types';

export const TECHNOLOGY_RULES: TechnologyRule[] = [
	{
		id: 'react',
		name: 'React',
		categories: ['web'],
		packages: ['react', 'react-dom'],
		skills: [
			'vercel-labs/agent-skills/react-best-practices',
			'vercel-labs/agent-skills/composition-patterns',
		],
		searchTerms: ['react', 'react typescript'],
	},
	{
		id: 'nextjs',
		name: 'Next.js',
		categories: ['web'],
		packages: ['next'],
		configFiles: ['next.config.js', 'next.config.mjs', 'next.config.ts'],
		skills: [
			'vercel-labs/next-skills/next-best-practices',
			'vercel-labs/next-skills/next-cache-components',
			'vercel-labs/next-skills/next-upgrade',
		],
		searchTerms: ['nextjs', 'next react'],
	},
	{
		id: 'typescript',
		name: 'TypeScript',
		categories: ['language', 'tooling'],
		packages: ['typescript'],
		configFiles: ['tsconfig.json'],
		fileExtensions: ['.ts', '.tsx'],
		skills: ['wshobson/agents/typescript-advanced-types'],
		searchTerms: ['typescript'],
	},
	{
		id: 'vscode-extension',
		name: 'VS Code Extension',
		categories: ['extension', 'tooling'],
		packages: ['@types/vscode', '@vscode/test-cli', '@vscode/test-electron'],
		configFiles: ['.vscode/launch.json', '.vscode/tasks.json'],
		skills: [
			'microsoft/vscode-github-skills/vscode-dev-workbench-skill-md',
			'wshobson/agents/typescript-advanced-types',
		],
		searchTerms: ['vscode extension', 'webview extension', 'extension host'],
	},
	{
		id: 'eslint',
		name: 'ESLint',
		categories: ['quality', 'tooling'],
		packages: ['eslint', 'typescript-eslint'],
		configFiles: ['eslint.config.js', 'eslint.config.mjs', '.eslintrc.js', '.eslintrc.cjs', '.eslintrc.json'],
		skills: ['wshobson/agents/typescript-advanced-types'],
		searchTerms: ['eslint', 'code quality', 'typescript lint'],
	},
	{
		id: 'tailwind',
		name: 'Tailwind CSS',
		categories: ['web', 'design'],
		packages: ['tailwindcss', '@tailwindcss/vite'],
		configFiles: ['tailwind.config.js', 'tailwind.config.ts', 'tailwind.config.cjs'],
		skills: ['giuseppe-trisciuoglio/developer-kit/tailwind-css-patterns'],
		searchTerms: ['tailwind css'],
	},
	{
		id: 'vite',
		name: 'Vite',
		categories: ['web', 'tooling'],
		packages: ['vite'],
		configFiles: ['vite.config.js', 'vite.config.ts', 'vite.config.mjs'],
		skills: ['antfu/skills/vite'],
		searchTerms: ['vite'],
	},
	{
		id: 'esbuild',
		name: 'esbuild',
		categories: ['tooling'],
		packages: ['esbuild'],
		configFiles: ['esbuild.js', 'esbuild.mjs', 'build.config.mjs'],
		skills: ['antfu/skills/vite'],
		searchTerms: ['esbuild', 'javascript build tooling'],
	},
	{
		id: 'vue',
		name: 'Vue',
		categories: ['web'],
		packages: ['vue'],
		skills: ['hyf0/vue-skills/vue-debug-guides', 'antfu/skills/vue', 'antfu/skills/vue-best-practices'],
		searchTerms: ['vue'],
	},
	{
		id: 'svelte',
		name: 'Svelte',
		categories: ['web'],
		packages: ['svelte', '@sveltejs/kit'],
		configFiles: ['svelte.config.js'],
		skills: ['ejirocodes/agent-skills/svelte5-best-practices', 'sveltejs/ai-tools/svelte-code-writer'],
		searchTerms: ['svelte'],
	},
	{
		id: 'astro',
		name: 'Astro',
		categories: ['web'],
		packages: ['astro'],
		configFiles: ['astro.config.mjs', 'astro.config.js', 'astro.config.ts'],
		skills: ['astrolicious/agent-skills/astro'],
		searchTerms: ['astro'],
	},
	{
		id: 'expo',
		name: 'Expo',
		categories: ['mobile'],
		packages: ['expo'],
		skills: [
			'expo/skills/building-native-ui',
			'expo/skills/native-data-fetching',
			'expo/skills/upgrading-expo',
			'expo/skills/expo-deployment',
		],
		searchTerms: ['expo react native'],
	},
	{
		id: 'react-native',
		name: 'React Native',
		categories: ['mobile'],
		packages: ['react-native'],
		skills: ['sleekdotdesign/agent-skills/design-mobile-apps'],
		searchTerms: ['react native mobile'],
	},
	{
		id: 'flutter',
		name: 'Flutter',
		categories: ['mobile'],
		configFiles: ['pubspec.yaml'],
		contentMatches: [{ files: ['pubspec.yaml'], terms: ['flutter:'] }],
		skills: [
			'jeffallan/claude-skills/flutter-expert',
			'madteacher/mad-agents-skills/flutter-animations',
			'madteacher/mad-agents-skills/flutter-testing',
		],
		searchTerms: ['flutter dart'],
	},
	{
		id: 'android',
		name: 'Android',
		categories: ['mobile'],
		configFiles: ['settings.gradle', 'settings.gradle.kts'],
		contentMatches: [{
			files: ['build.gradle', 'build.gradle.kts', 'app/build.gradle', 'app/build.gradle.kts'],
			terms: ['com.android.application', 'com.android.library', 'org.jetbrains.kotlin.android'],
		}],
		skills: [
			'krutikJain/android-agent-skills/android-kotlin-core',
			'krutikJain/android-agent-skills/android-compose-foundations',
			'krutikJain/android-agent-skills/android-architecture-clean',
		],
		searchTerms: ['android kotlin'],
	},
	{
		id: 'python',
		name: 'Python',
		categories: ['backend', 'language'],
		configFiles: ['pyproject.toml', 'requirements.txt', 'Pipfile'],
		fileExtensions: ['.py'],
		skills: ['wshobson/agents/python-pro'],
		searchTerms: ['python'],
	},
	{
		id: 'fastapi',
		name: 'FastAPI',
		categories: ['backend'],
		packages: ['fastapi'],
		contentMatches: [{ files: ['pyproject.toml', 'requirements.txt'], terms: ['fastapi'] }],
		skills: ['wshobson/agents/api-documenter'],
		searchTerms: ['fastapi python api'],
	},
	{
		id: 'node',
		name: 'Node.js',
		categories: ['backend'],
		configFiles: ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', '.nvmrc', '.node-version'],
		skills: ['wshobson/agents/nodejs-backend-patterns', 'sickn33/antigravity-awesome-skills/nodejs-best-practices'],
		searchTerms: ['nodejs backend'],
	},
	{
		id: 'prisma',
		name: 'Prisma',
		categories: ['database'],
		packages: ['prisma', '@prisma/client'],
		configFiles: ['prisma/schema.prisma'],
		skills: ['prisma/skills/prisma-database-setup', 'prisma/skills/prisma-client-api', 'prisma/skills/prisma-cli'],
		searchTerms: ['prisma database'],
	},
	{
		id: 'supabase',
		name: 'Supabase',
		categories: ['database'],
		packages: ['@supabase/supabase-js', '@supabase/ssr'],
		skills: ['supabase/agent-skills/supabase-postgres-best-practices'],
		searchTerms: ['supabase postgres'],
	},
	{
		id: 'playwright',
		name: 'Playwright',
		categories: ['testing'],
		packages: ['@playwright/test', 'playwright'],
		configFiles: ['playwright.config.ts', 'playwright.config.js'],
		skills: ['currents-dev/playwright-best-practices-skill/playwright-best-practices'],
		searchTerms: ['playwright testing'],
	},
	{
		id: 'vitest',
		name: 'Vitest',
		categories: ['testing'],
		packages: ['vitest'],
		configFiles: ['vitest.config.ts', 'vitest.config.js', 'vitest.config.mts'],
		skills: ['antfu/skills/vitest'],
		searchTerms: ['vitest testing'],
	},
	{
		id: 'mocha',
		name: 'Mocha',
		categories: ['testing'],
		packages: ['mocha', '@types/mocha'],
		skills: ['currents-dev/playwright-best-practices-skill/playwright-best-practices'],
		searchTerms: ['mocha testing', 'typescript testing'],
	},
	{
		id: 'bun',
		name: 'Bun',
		categories: ['tooling'],
		configFiles: ['bun.lock', 'bun.lockb', 'bunfig.toml'],
		skills: ['midudev/autoskills/bun'],
		searchTerms: ['bun'],
	},
	{
		id: 'agent-skills',
		name: 'Agent Skills',
		categories: ['ai', 'tooling', 'docs'],
		configFiles: ['skills-lock.json', '.agents/skills', '.claude/skills', 'AGENTS.md'],
		skills: [],
		searchTerms: ['agent skills', 'skill discovery'],
	},
	{
		id: 'cloudflare',
		name: 'Cloudflare',
		categories: ['infra', 'backend'],
		packages: ['wrangler', '@cloudflare/workers-types'],
		configFiles: ['wrangler.toml', 'wrangler.json', 'wrangler.jsonc'],
		skills: ['cloudflare/skills/cloudflare', 'cloudflare/skills/wrangler', 'cloudflare/skills/workers-best-practices'],
		searchTerms: ['cloudflare workers'],
	},
	{
		id: 'vercel',
		name: 'Vercel',
		categories: ['infra', 'web', 'backend'],
		packages: ['vercel', '@astrojs/vercel'],
		configFiles: ['vercel.json', '.vercel/project.json'],
		skills: ['vercel-labs/agent-skills/deploy-to-vercel'],
		searchTerms: ['vercel deployment'],
	},
	{
		id: 'netlify',
		name: 'Netlify',
		categories: ['infra', 'web', 'backend'],
		packages: ['netlify-cli', '@netlify/functions'],
		configFiles: ['netlify.toml'],
		skills: [],
		searchTerms: ['netlify deployment'],
	},
];
